### ISSUE TITLE
struct.error: unpack requires a buffer of 4 bytes

### ISSUE THREAD

**Issue by bindwood2008** [K0lb3/Romancing-SaGa-Re-univerSe-asset-downloader#2]
when I run the "download_assets.py", it works for "master" part but fails in "texture" part

 File "Anaconda3\envs\eric\lib\site-packages\UnityPy\streams\EndianBinaryReader.py", line 51, in read_int
    return unpack(self.endian + "i", self.read(4))[0]
struct.error: unpack requires a buffer of 4 bytes

File "Anaconda3\envs\eric\lib\multiprocessing\pool.py", line 870, in next
    raise value
struct.error: unpack requires a buffer of 4 bytes

**Comment by K0lb3** [comment]
The issue was related to a problem in UnityPy 1.7.30 ~ 1.7.32.
The new version 1.7.33 fixes the issue.
